services:
  postgres:
    image: postgres:15
    container_name: van-edu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-van_edu_db}
      POSTGRES_USER: ${POSTGRES_USER:-van_edu_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password_change_me}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TIMEZONE:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
      - ./scripts/init:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./backups:/backups
    networks:
      - van-edu-db-network
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c shared_preload_libraries=pg_stat_statements
      -c log_statement=all
      -c log_min_duration_statement=2000
      -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-van_edu_app} -d ${POSTGRES_DB:-van_edu_db}"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: van-edu-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@vanedu.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    networks:
      - van-edu-db-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev

volumes:
  postgres_data:
    name: van-edu-postgres-data
  postgres_logs:
    name: van-edu-postgres-logs

networks:
  van-edu-db-network:
    name: van-edu-db-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16 