version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: van-edu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password_change_me}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-van_edu_db}
      MYSQL_USER: ${MYSQL_USER:-van_edu_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user_password_change_me}
      TZ: ${TIMEZONE:-UTC}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./scripts/init:/docker-entrypoint-initdb.d
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./backups:/backups
    networks:
      - van-edu-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=512M
      --max-connections=200
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password_change_me}"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: van-edu-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-van_edu_user}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-user_password_change_me}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password_change_me}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    networks:
      - van-edu-network
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - dev

volumes:
  mysql_data:
    name: van-edu-mysql-data
  mysql_logs:
    name: van-edu-mysql-logs

networks:
  van-edu-network:
    name: van-edu-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 